/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alquerque;

public class App {

    public static void main(String[] args) {
        // play the game here
        Board board = new Board(null, null);
        board.display();
    }

}
